name: Build and publish nuget packages

on:
  push:
    branches:
    - main

  #release:
  #  types:
  #    - published

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install dependencies
      run: dotnet tool restore

    - name: Test
      run: dotnet fsi ./build.fsx

    - name: Publish nuget packages
      run: |
        dotnet pack -c Release Fun.I18n.Provider.Fable/Fun.I18n.Provider.Fable.fsproj -o .
        dotnet pack -c Release Fun.I18n.Provider/Fun.I18n.Provider.fsproj -o .
        dotnet pack -c Release Fun.I18n/Fun.I18n.fsproj -o .
        dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
